keys:
  - &key age1fnlpe6k68mwuvg5typxsj2rj8le9x5pqu2apz6v3z8q8rps0u3dqmqdrdk
  - &key2 age1r5xkcjtp2wzr63fg356d9l700v50elek0ps0csujuyfhq4zm8cuqxdysqx
creation_rules:
  - path_regex: secrets\.(yaml|json)$  
    key_groups:
      - age:
          - *key
          - *key2
