keys:
  - &key1 age1r5xkcjtp2wzr63fg356d9l700v50elek0ps0csujuyfhq4zm8cuqxdysqx
  - &key2 age1y93elfw25fk444d8dvy8hv00693evlzj3t6yh506uxq0tjxek57qn97xxf
creation_rules:
  - path_regex: secrets\.(yaml|json)$  
    key_groups:
      - age:
          - *key1
          - *key2
