#!/bin/env bash

systemctl --failed
paccache -ruk0
sudo pacman -Qqd | sudo pacman -Rsu -
sudo pacman -Qqe >~/dotfiles/install/pkglist.txt
cd ~/dotfiles/
stow .
git add .
git commit -a -m "Dotfiles update"
git push

sudo timeshift --check
