
format = """
$directory\
$python\
$git_branch\
$character\
"""

right_format = """
$sudo\
"""

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[❯](bold green)" 
error_symbol = "[❯](bold red)"

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}$virtualenv]($style) '

[sudo]
format = "[$symbol]($style)"
style = "bold yellow"
symbol = " "
disabled = false

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
# format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
format = "[$hostname](bold red) "
# trim_at = ".companyname.com"
disabled = true

[username]
#style_user = "white bold"
style_user = "aqua bold"
style_root = "black bold"
format = "[$user]($style)@"
#format = "[$user : ]($style)"
# format = "[🚀 : ]($style)"
disabled = true
show_always = true

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "blue"
# format = "[git:](bold lavender)[\\(](bold lavender)[$branch(:$remote_branch)]($style)[\\)](bold lavender) "

[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
read_only = " "
truncation_length = 4
home_symbol = "~"
style = "green"


